const stickerImages = {
    1: require('./images/sticker1.webp'),
    2: require('./images/sticker2.webp'),
    3: require('./images/sticker3.webp'),
    4: require('./images/sticker4.webp'),
    5: require('./images/sticker5.webp'),
    6: require('./images/sticker6.webp'),
    7: require('./images/sticker7.webp'),
    8: require('./images/sticker8.webp'),
    9: require('./images/sticker9.webp'),
    10: require('./images/sticker10.webp'),
    11: require('./images/sticker11.webp'),
    12: require('./images/sticker12.webp'),
    13: require('./images/sticker13.webp'),
    14: require('./images/sticker14.webp'),
    15: require('./images/sticker15.webp'),
    16: require('./images/sticker16.webp'),
    17: require('./images/sticker17.webp'),
    18: require('./images/sticker18.webp'),
    19: require('./images/sticker19.webp'),
    20: require('./images/sticker20.webp'),
    21: require('./images/sticker21.webp'),
    22: require('./images/sticker22.webp'),
    23: require('./images/sticker23.webp'),
    24: require('./images/sticker24.webp'),
};

export default stickerImages;
