const stickersData = [
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker1.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker2.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker3.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker4.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker5.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker6.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker7.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker8.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker9.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker10.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker11.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker12.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker13.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker14.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker15.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker16.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker17.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker18.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker19.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker20.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker21.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker22.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker23.webp` },
    { image: `${process.env.PUBLIC_URL}/images/stickers/sticker24.webp` },
];

export default stickersData;
