const stickersData = [
    { image: require('./images/sticker1.webp') },
    { image: require('./images/sticker2.webp') },
    { image: require('./images/sticker3.webp') },
    { image: require('./images/sticker4.webp') },
    { image: require('./images/sticker5.webp') },
    { image: require('./images/sticker6.webp') },
    { image: require('./images/sticker7.webp') },
    { image: require('./images/sticker8.webp') },
    { image: require('./images/sticker9.webp') },
    { image: require('./images/sticker10.webp') },
    { image: require('./images/sticker11.webp') },
    { image: require('./images/sticker12.webp') },
    { image: require('./images/sticker13.webp') },
    { image: require('./images/sticker14.webp') },
    { image: require('./images/sticker15.webp') },
    { image: require('./images/sticker16.webp') },
    { image: require('./images/sticker17.webp') },
    { image: require('./images/sticker18.webp') },
    { image: require('./images/sticker19.webp') },
    { image: require('./images/sticker20.webp') },
    { image: require('./images/sticker21.webp') },
    { image: require('./images/sticker22.webp') },
    { image: require('./images/sticker23.webp') },
    { image: require('./images/sticker24.webp') },
];

export default stickersData;
