const stickersData = [
    { image: `${process.env.PUBLIC_URL}/images/sticker1.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker2.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker3.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker4.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker5.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker6.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker7.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker8.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker9.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker10.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker11.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker12.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker13.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker14.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker15.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker16.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker17.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker18.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker19.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker20.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker21.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker22.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker23.webp` },
    { image: `${process.env.PUBLIC_URL}/images/sticker24.webp` },
];

export default stickersData;
